=head1 NAME

Convos API specification

=head1 VERSION

0.87

=head1 DESCRIPTION

This document describes the API for Convos, a multiuser persistent IRC proxy with web interface.

=head1 TERMS OF SERVICE

SSL (HTTPS) is highly suggested, since login credentials and session cookies are transmitted over this API.

=head1 BASEURL

L<http://demo.convos.by/1.0>

=head1 RESOURCES

=head2 commandList

Get list of available ommands.

=head3 Resource URL

  GET http://demo.convos.by/1.0/commands

=head3 Parameters

This resource takes no parameters.

=head3 Responses

=head4 200 - OK

List of commands.

  [
    {
      "command": string, // required
      "id": string, // required
    },
    ...
  ]

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 connection

Get information about a connection.

=head3 Resource URL

  GET http://demo.convos.by/1.0/connection/{protocol}/{connection_id}

=head3 Parameters

  .--------------------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                          |
  |--------------------------------------------------------------------------------------|
  | connection_id    | path   | string | Yes      | A friendly name of the server        |
  | protocol         | path   | string | Yes      | The name of the connection protocol. |
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now.           |
  '--------------------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

A single connection.

  {
    "connection_id":     {// required
      "required":     },
    "name": string, // No description.
    "nick":     {// required
      "required":     },
    "path": string, // No description.
    "server":     {// required
      "required":     },
    "state": string, // No description.
    "url": string, // No description.
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 connectionAdd

Add a connection.

=head3 Resource URL

  POST http://demo.convos.by/1.0/connection

=head3 Parameters

  .----------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                |
  |----------------------------------------------------------------------------|
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now. |
  | data             | body   | schema | Yes      | No description.            |
  '----------------------------------------------------------------------------'

  data:

  {
    "password": string, // Login password to server.
    "protocol": string, // Protocol to use. Example: IRC.
    "server": string, // Either complete url or server:port. (Port is optional)
    "username": string, // Login username to server.
  },

=head3 Responses

=head4 200 - OK

Connection information.

  {
    "connection_id":     {// required
      "required":     },
    "name": string, // No description.
    "nick":     {// required
      "required":     },
    "path": string, // No description.
    "server":     {// required
      "required":     },
    "state": string, // No description.
    "url": string, // No description.
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 connectionDelete

Delete a connection and all assosiated data.

=head3 Resource URL

  DELETE http://demo.convos.by/1.0/connection/{protocol}/{connection_id}

=head3 Parameters

  .--------------------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                          |
  |--------------------------------------------------------------------------------------|
  | connection_id    | path   | string | Yes      | A friendly name of the server        |
  | protocol         | path   | string | Yes      | The name of the connection protocol. |
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now.           |
  '--------------------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

Delete a connection.

  {
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 connectionRooms

Get a list of all available chat rooms.

=head3 Resource URL

  GET http://demo.convos.by/1.0/connection/{protocol}/{connection_id}/rooms

=head3 Parameters

  .--------------------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                          |
  |--------------------------------------------------------------------------------------|
  | connection_id    | path   | string | Yes      | A friendly name of the server        |
  | protocol         | path   | string | Yes      | The name of the connection protocol. |
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now.           |
  '--------------------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

List of rooms.

  [
    {
      "name": string, // No description.
      "path": string, // No description.
      "topic": string, // No description.
      "users":       {
        "name": string, // Name of the user
      },
    },
    ...
  ]

=head4 Default

Internal server error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 connectionUpdate

Update a connection.

=head3 Resource URL

  POST http://demo.convos.by/1.0/connection/{protocol}/{connection_id}

=head3 Parameters

  .--------------------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                          |
  |--------------------------------------------------------------------------------------|
  | connection_id    | path   | string | Yes      | A friendly name of the server        |
  | protocol         | path   | string | Yes      | The name of the connection protocol. |
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now.           |
  | data             | body   | schema | Yes      | No description.                      |
  '--------------------------------------------------------------------------------------'

  data:

  {
    "connection_id":     {// required
      "required":     },
    "name": string, // No description.
    "nick":     {// required
      "required":     },
    "path": string, // No description.
    "server":     {// required
      "required":     },
    "state": string, // No description.
    "url": string, // No description.
  },

=head3 Responses

=head4 200 - OK

Update a connection.

  {
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 connections

Get all the connections for a user.

=head3 Resource URL

  GET http://demo.convos.by/1.0/connections

=head3 Parameters

  .----------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                |
  |----------------------------------------------------------------------------|
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now. |
  '----------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

List of connections.

  [
    {
      "connection_id":       {// required
        "required":       },
      "name": string, // No description.
      "nick":       {// required
        "required":       },
      "path": string, // No description.
      "server":       {// required
        "required":       },
      "state": string, // No description.
      "url": string, // No description.
    },
    ...
  ]

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 conversationMessages

Get a list of messages.

Note: this resource require the user to be authenticated first.

=head3 Resource URL

  GET http://demo.convos.by/1.0/connection/{protocol}/{connection_id}/conversation/{conversation_id}/messages

=head3 Parameters

  .---------------------------------------------------------------------------------------.
  | Name            | In   | Type   | Required | Description                              |
  |---------------------------------------------------------------------------------------|
  | connection_id   | path | string | Yes      | A friendly name of the server            |
  | conversation_id | path | string | No       | The name of the person/chat conversation |
  '---------------------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

List of messsages.

  [
    {
      "id": string, // required
      "message": string, // required
      "timestamp": int32, // required
    },
    ...
  ]

=head4 Default

Internal server error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 conversationSend

Send a message to a target.

=head3 Resource URL

  POST http://demo.convos.by/1.0/connection/{protocol}/{connection_id}/conversation/{conversation_id}/send

=head3 Parameters

  .------------------------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                              |
  |------------------------------------------------------------------------------------------|
  | connection_id    | path   | string | Yes      | A friendly name of the server            |
  | conversation_id  | path   | string | No       | The name of the person/chat conversation |
  | protocol         | path   | string | Yes      | The name of the connection protocol.     |
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now.               |
  '------------------------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

No description.

  {
    "command": string, // required
    "id": string, // required
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 conversations

Get a list of all conversations.

=head3 Resource URL

  GET http://demo.convos.by/1.0/conversations

=head3 Parameters

  .----------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                |
  |----------------------------------------------------------------------------|
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now. |
  '----------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

List of messsages.

  [
    {
      "name": string, // No description.
      "path": string, // No description.
      "topic": string, // No description.
      "users":       {
        "name": string, // Name of the user
      },
    },
    ...
  ]

=head4 Default

Internal server error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 notificationSeen

Mark a notication as seen.

TODO: Notification count vs red/green toggling of a single notification.

=head3 Resource URL

  POST http://demo.convos.by/1.0/notifications/seen

=head3 Parameters

  .----------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                |
  |----------------------------------------------------------------------------|
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now. |
  | data             | body   | schema | Yes      | List of notification IDs.  |
  '----------------------------------------------------------------------------'

  data:

  {
  },

=head3 Responses

=head4 200 - OK

List of commands.

  [
    {
      "id": string, // required
      "message": string, // required
      "timestamp": int32, // required
    },
    ...
  ]

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 notifications

Get list of notications.

A notification is added once your name is mentioned in a chat or someone sends a direct message.

=head3 Resource URL

  GET http://demo.convos.by/1.0/notifications

=head3 Parameters

  .----------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                |
  |----------------------------------------------------------------------------|
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now. |
  '----------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

List of commands.

  [
    {
      "id": string, // required
      "message": string, // required
      "timestamp": int32, // required
    },
    ...
  ]

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 user

Get user data.

=head3 Resource URL

  GET http://demo.convos.by/1.0/user

=head3 Parameters

  .----------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                |
  |----------------------------------------------------------------------------|
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now. |
  '----------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

User profile.

  {
    "avatar": string, // No description.
    "email": string, // No description.
    "links":     [
      {
        "href": url, // required
        "rel": string, // required
      },
      ...
    ]
    "registered": integer, // No description.
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 userDelete

Delete a user.

=head3 Resource URL

  DELETE http://demo.convos.by/1.0/user

=head3 Parameters

  .----------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                |
  |----------------------------------------------------------------------------|
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now. |
  '----------------------------------------------------------------------------'

=head3 Responses

=head4 200 - OK

Successfully deleted.

  {
    "links":     [
      {
        "href": url, // required
        "rel": string, // required
      },
      ...
    ]
    "message": string, // No description.
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 userLogin

Log in a user based on email and password.

=head3 Resource URL

  POST http://demo.convos.by/1.0/user/login

=head3 Parameters

  .---------------------------------------------------.
  | Name | In   | Type   | Required | Description     |
  |---------------------------------------------------|
  | data | body | schema | Yes      | No description. |
  '---------------------------------------------------'

  data:

  {
    "email": email, // User email
    "password": string, // User password
  },

=head3 Responses

=head4 200 - OK

User profile.

  {
    "avatar": string, // No description.
    "email": string, // No description.
    "links":     [
      {
        "href": url, // required
        "rel": string, // required
      },
      ...
    ]
    "registered": integer, // No description.
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 userRegister

Register a new user.

=head3 Resource URL

  POST http://demo.convos.by/1.0/user/register

=head3 Parameters

  .---------------------------------------------------.
  | Name | In   | Type   | Required | Description     |
  |---------------------------------------------------|
  | data | body | schema | Yes      | No description. |
  '---------------------------------------------------'

  data:

  {
    "avatar": string, // User avatar
    "email": email, // User email
    "password": string, // User password
  },

=head3 Responses

=head4 200 - OK

User profile.

  {
    "avatar": string, // No description.
    "email": string, // No description.
    "links":     [
      {
        "href": url, // required
        "rel": string, // required
      },
      ...
    ]
    "registered": integer, // No description.
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head2 userSave

Update an existing user.

=head3 Resource URL

  POST http://demo.convos.by/1.0/user

=head3 Parameters

  .----------------------------------------------------------------------------.
  | Name             | In     | Type   | Required | Description                |
  |----------------------------------------------------------------------------|
  | X-Convos-Session | header | string | No       | TODO. Use cookies for now. |
  | data             | body   | schema | Yes      | No description.            |
  '----------------------------------------------------------------------------'

  data:

  {
    "avatar": string, // User avatar
    "password": string, // User password
  },

=head3 Responses

=head4 200 - OK

User profile.

  {
    "avatar": string, // No description.
    "email": string, // No description.
    "links":     [
      {
        "href": url, // required
        "rel": string, // required
      },
      ...
    ]
    "registered": integer, // No description.
  },

=head4 Default

Error.

  {
    "code":     {// required
      "required":     },
    "errors":     [
      {
        "message": string, // No description.
        "path": string, // No description.
      },
      ...
    ]
    "message":     {// required
      "required":     },
  },

=head1 COPYRIGHT AND LICENSE

Convos - https://github.com/Nordaaker/convos

Artistic License version 2.0 - http://opensource.org/licenses/Artistic-2.0

=cut
