#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use File::Spec;
use lib "$FindBin::Bin/../lib";

$ENV{MOJO_MODE} or die "You cannot invoke $0 directly. Use 'convos backend' instead\n";

require Convos::Control::Backend;
exit Convos::Control::Backend->new->run;
