#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";

$ENV{CONVOS_BACKEND_ONLY} = 1;
$ENV{MOJO_MODE} or die "You cannot invoke $0 directly. Use 'convos backend' instead\n";

require Mojolicious::Commands;
require Convos;
my $commands = Mojolicious::Commands->new(app => Convos->new);
unshift @{$commands->namespaces}, 'Convos::Command';
$commands->run(backend => @ARGV);
