#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use File::Spec;
use lib "$FindBin::Bin/../lib";
$ENV{CONVOS_FRONTEND_PID_FILE} ||= File::Spec->catfile(File::Spec->tmpdir, 'convos-frontend.pid');
$ENV{MOJO_MODE} or die "You cannot invoke $0 directly. Use 'convos frontend' instead\n";
require Convos::Control::Frontend;
exit Convos::Control::Frontend->new->run;
