#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";

# Start commands for application
require Mojolicious::Commands;
require WebIrc;
my $commands = Mojolicious::Commands->new(app => WebIrc->new);
push @{$commands->namespaces}, 'WebIrc::Command';
$commands->run(@ARGV);
