name: convos
version: '5.26.0'
summary: Multiuser chat application that runs in your web browser
description: |
  The supported chat protocol is currently IRC.
  See http://convos.chat for more details.
icon: assets/images/convos-icon.svg

base: core20
type: app
grade: stable
confinement: strict # devmode or strict
architectures:
  - amd64

parts:
  convos:
    source: .
    plugin: dump
    stage:
      - -.ackrc
      - -.git
      - -.gitignore
      - -.perltidyrc
      - -.ship.conf
      - -Dockerfile
      - -script/parse-irc-message.pl
      - -t
    build-packages:
      - gcc
      - libc6-dev
      - make
      - libnet-ssleay-perl
      - libio-socket-ssl-perl
      - perl-base
      - perl-modules
    stage-packages:
      - libnet-ssleay-perl
      - libio-socket-ssl-perl
      - perl-base
      - perl-modules
    override-build: |
      set -x
      perl ./script/convos install

      chmod +x script/snap.sh
      cp script/snap.sh $SNAPCRAFT_PART_INSTALL/.

      snapcraftctl build

apps:
  convos:
    command: snap.sh
    plugs:
      - home
      - network
      - network-bind
